[build]
  command = "npm run build"
  publish = "dist"

# React SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy hacia Railway
[[redirects]]
  from = "/api/*"
  to = "https://backendeventoticket-production.up.railway.app/api/:splat"
  status = 200
  force = true
